-- Bazaario — orders table for the Buy Now checkout flow.
-- Run this once in your Supabase project's SQL editor, in addition to
-- seller-ownership.sql (it reads public.products.owner_id and public.profiles).
-- Safe to re-run: every statement uses IF NOT EXISTS / OR REPLACE /
-- DROP ... IF EXISTS. Re-running it on a database that already has orders
-- adds the seller columns/trigger/policy below and leaves existing rows alone.
--
-- Orders use human-readable ids generated by the app (e.g. "BZ-ABC123-045"),
-- so `id` is text rather than uuid. Order line items and customer details
-- are stored as jsonb snapshots at the time of purchase, so an order stays
-- readable even if the underlying product listing is later edited or removed.
--
-- Seller ownership: every line in `items` carries a `sellerId` (the product's
-- owner_id at purchase time, or null). It is stamped by a database trigger
-- from public.products — whatever the client sends is overwritten — and
-- `seller_ids` is derived from it, so a seller can be given read access to
-- exactly the orders that contain one of their products.
--
-- Seller READ access goes through the view public.seller_orders (below), NOT
-- through a select policy on public.orders. A row-level policy can only return
-- the whole order, which for a multi-seller order would hand Seller A the items
-- of Seller B. The view returns only the caller's own lines.

create table if not exists public.orders (
  id text primary key,
  created_at timestamptz not null default now(),
  status text not null default 'Placed',
  items jsonb not null default '[]'::jsonb,
  subtotal numeric not null default 0,
  delivery numeric not null default 0,
  total numeric not null default 0,
  customer jsonb not null default '{}'::jsonb,
  payment_method text not null default '',
  buyer_id uuid references auth.users (id) on delete set null,
  -- Derived from items[].sellerId by the trigger below; never written by the app.
  seller_ids uuid[] not null default '{}'::uuid[]
);

-- For projects that created `orders` before seller ownership existed.
alter table public.orders add column if not exists seller_ids uuid[] not null default '{}'::uuid[];

-- Lets "orders containing one of my products" (seller_ids @> array[uid]) use an index.
create index if not exists orders_seller_ids_idx on public.orders using gin (seller_ids);

alter table public.orders enable row level security;

-- Signed-in buyers can see their own orders; admins can see every order.
drop policy if exists "orders: read own or admin" on public.orders;
create policy "orders: read own or admin"
  on public.orders for select
  using (
    auth.uid() = buyer_id
    or exists (select 1 from public.profiles where id = auth.uid() and is_admin)
  );

-- Sellers do NOT read public.orders directly any more. An earlier version of this
-- file had an "orders: read as seller" policy here; it returned the whole row, so
-- on an order containing two sellers' products each seller received the other's
-- items through the REST API. It is dropped, and sellers read through the
-- public.seller_orders view defined further down. (Buyer/admin access above is
-- unchanged.)
drop policy if exists "orders: read as seller" on public.orders;

-- Anyone (including guest checkout, i.e. no signed-in session) can place an
-- order, as long as they don't claim to be a different buyer than themselves.
drop policy if exists "orders: insert own or guest" on public.orders;
create policy "orders: insert own or guest"
  on public.orders for insert
  with check (buyer_id is null or auth.uid() = buyer_id);

-- Buyers can update (e.g. cancel) their own orders; admins can update any order.
drop policy if exists "orders: update own or admin" on public.orders;
create policy "orders: update own or admin"
  on public.orders for update
  using (
    auth.uid() = buyer_id
    or exists (select 1 from public.profiles where id = auth.uid() and is_admin)
  );

-- ---------------------------------------------------------------------------
-- Seller stamping. The client sends a `sellerId` on each line for its own
-- convenience, but the database never believes it: on every insert it is
-- replaced with public.products.owner_id for that line's product id
-- (null when the product doesn't exist, e.g. deleted or sample/seed ids).
-- ---------------------------------------------------------------------------

create or replace function public.stamp_order_items(p_items jsonb)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'orders.items must be a JSON array';
  end if;

  if exists (
    select 1 from jsonb_array_elements(p_items) as e(elem)
    where jsonb_typeof(e.elem) <> 'object'
  ) then
    raise exception 'every order item must be a JSON object';
  end if;

  return coalesce(
    (
      select jsonb_agg(
               (e.elem - 'sellerId') || jsonb_build_object('sellerId', p.owner_id)
               order by e.ord
             )
      from jsonb_array_elements(p_items) with ordinality as e(elem, ord)
      -- Compared as text so this works whether products.id is uuid (what
      -- seller-ownership.sql creates) or text: a uuid-typed comparison would make
      -- every checkout fail with "operator does not exist: text = uuid" on a
      -- database whose products.id is text. uuid::text is always lower-case, so a
      -- uuid-looking id is lower-cased before comparing; other ids match exactly.
      left join public.products p
        on p.id::text = case
                          when e.elem ->> 'id' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
                          then lower(e.elem ->> 'id')
                          else e.elem ->> 'id'
                        end
    ),
    '[]'::jsonb
  );
end;
$$;

-- Not callable through the REST API; only the trigger below (and you, in the
-- SQL editor) use it.
revoke all on function public.stamp_order_items(jsonb) from public, anon, authenticated;

create or replace function public.orders_guard_items()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_is_admin boolean := false;
begin
  if tg_op = 'UPDATE' then
    -- Items untouched (e.g. a status change): keep seller_ids exactly as it was,
    -- so nobody can PATCH it directly.
    if new.items is not distinct from old.items then
      new.seller_ids := old.seller_ids;
      return new;
    end if;

    -- Items are being changed. A signed-in API caller may only do that as an
    -- admin; otherwise a buyer could rewrite sellerId on their own order after
    -- placing it. (auth.uid() is null in the SQL editor, which stays allowed.)
    if auth.uid() is not null then
      select exists (
        select 1 from public.profiles where id = auth.uid() and is_admin
      ) into v_is_admin;

      if not v_is_admin then
        raise exception 'Order items cannot be changed after the order is placed.'
          using errcode = '42501';
      end if;
    end if;
  end if;

  -- INSERT, or an admin/SQL-editor change to items: (re)stamp from products.
  new.items := public.stamp_order_items(new.items);
  new.seller_ids := array(
    select distinct (elem ->> 'sellerId')::uuid
    from jsonb_array_elements(new.items) as elem
    where elem ->> 'sellerId' is not null
  );
  return new;
end;
$$;

revoke all on function public.orders_guard_items() from public, anon, authenticated;

drop trigger if exists orders_guard_items on public.orders;
create trigger orders_guard_items
  before insert or update on public.orders
  for each row execute function public.orders_guard_items();

-- Makes the text-typed product lookup above use an index (harmless if products.id
-- is already text). uuid -> text is immutable, so this expression index is valid.
create index if not exists products_id_text_idx on public.products ((id::text));

-- ---------------------------------------------------------------------------
-- public.seller_orders — the ONLY way a seller reads orders.
--
--   * Identity comes from auth.uid() (the verified JWT). There is no seller-id
--     parameter or column a client could change, so `?sellerId=<someone else>`
--     (or any other filter) can only narrow what the caller is already allowed
--     to see, never widen it.
--   * A row appears only if seller_ids contains the caller.
--   * `items` is rebuilt to hold ONLY the caller's own lines, so the other
--     seller's items never leave the database. `total`, `subtotal`, `delivery`,
--     `buyer_id` and `seller_ids` are not exposed at all.
--   * Legacy orders (seller_ids = '{}') match nobody.
--   * security_barrier stops a caller-supplied filter/function from being
--     evaluated before the auth.uid() check.
--
-- The view runs with its owner's rights (so it can read public.orders without a
-- seller policy on it) — that is intentional; the auth.uid() conditions above are
-- the access check. Supabase's linter will flag "security definer view": expected.
-- Anonymous callers have no privilege on it.
-- ---------------------------------------------------------------------------

create or replace view public.seller_orders
with (security_barrier = true) as
select
  o.id,
  o.created_at,
  o.status,
  o.payment_method,
  o.customer,
  (
    select coalesce(jsonb_agg(e.elem order by e.ord), '[]'::jsonb)
    from jsonb_array_elements(
           case when jsonb_typeof(o.items) = 'array' then o.items else '[]'::jsonb end
         ) with ordinality as e(elem, ord)
    where e.elem ->> 'sellerId' = auth.uid()::text
  ) as items
from public.orders o
where o.seller_ids @> array[auth.uid()];

revoke all on public.seller_orders from public, anon, authenticated;
grant select on public.seller_orders to authenticated;

-- ---------------------------------------------------------------------------
-- OPTIONAL, run by hand only if you want it: give sellers visibility of orders
-- placed BEFORE this migration. Old lines have no sellerId, so by default those
-- orders stay visible to the buyer and admins only. This backfill uses each
-- product's CURRENT owner_id, which may not be who actually sold it if the
-- listing changed hands or was deleted (deleted products stay unassigned) —
-- and it lets that seller read the buyer's delivery details — so it is left
-- commented out on purpose.
--
--   update public.orders
--      set items = public.stamp_order_items(items)
--    where seller_ids = '{}'::uuid[];
-- ---------------------------------------------------------------------------

-- Note: guest orders (buyer_id is null) are written to the database for
-- durable storage, but — because there is no signed-in user to match against
-- — they cannot be read back through this API afterwards except by an admin
-- (and, through public.seller_orders, the seller who owns the product — who sees
-- only their own lines of it).
-- The app keeps a local copy in the buyer's browser so a guest can still
-- track the order they just placed on the same device.
--
-- Because guests can't read the row back, the app inserts orders with
-- `Prefer: return=minimal`. With `return=representation` Postgres would also
-- check the new row against the SELECT policies and reject the guest's insert.
